// web/build.ts

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import * as esbuild from "esbuild";
import { STYLES } from "./styles";

async function build() {
  const result = await esbuild.build({
    entryPoints: ["web/app.ts"],
    bundle: true,
    minify: true,
    format: "iife",
    target: ["es2022"],
    write: false,
  });

  const js = result.outputFiles[0].text;
  const html = readFileSync("web/index.html", "utf-8");
  const faviconBase64 = readFileSync("web/assets/favicon-64.png").toString("base64");
  const faviconDataUri = `data:image/png;base64,${faviconBase64}`;
  const output = html
    .replace("/* __INJECTED_CSS__ */", STYLES)
    .replace("/* __INJECTED_JS__ */", js)
    .replace("/* __INJECTED_FAVICON__ */", faviconDataUri);

  mkdirSync("dist", { recursive: true });
  writeFileSync("dist/chunker.html", output);
  console.log(`Built dist/chunker.html (${output.length} bytes)`);

  writeFileSync(
    "src/html.ts",
    `// AUTO-GENERATED by web/build.ts — do not edit\nexport const CHUNKER_HTML = ${JSON.stringify(output)};\n`,
  );
  console.log("Generated src/html.ts");
}

build();
